### ISSUE TITLE
Reg: Preselect name?

### ISSUE THREAD

**Issue by fetmar** [ICTatRTI/coconut#27] opened 2013-10-11 15:31 UTC
Hierarchy for Municipio and Barrio. Could we preselect the name according to a hierarchy of Provincia?

**Comment by carl-fisher** [comment] 2013-10-28 18:57
Wayne says, "If I understand correctly, we should make the on-line system logical so that the drop down lists will work. It will be a pain for data entry in the beginning. We can adjust the paper forms later."

**Comment by vbakalov** [comment] 2013-11-07 15:17
This was a duplicate of another already closed bug.

**Closed as completed by vbakalov** 2013-11-07 15:17 UTC
